# Generated by Django 3.2.5 on 2021-08-25 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FriendApp', '0005_alter_friendlist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='sender',
        ),
        migrations.DeleteModel(
            name='FriendList',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
