# Generated by Django 3.2.5 on 2021-07-31 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatthread',
            name='thread',
        ),
        migrations.AddField(
            model_name='chatthread',
            name='thread',
            field=models.ManyToManyField(related_name='thread', to='chatApp.Message'),
        ),
        migrations.RemoveField(
            model_name='chatthread',
            name='user',
        ),
        migrations.AddField(
            model_name='chatthread',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
