# Generated by Django 3.2.5 on 2021-07-31 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0002_auto_20210731_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='ChatThread',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
